name = "testhone"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[site]
bucket = ".next" 